### ISSUE TITLE
Notes page has no content

### ISSUE THREAD

**Issue by agarmu** [project-mae/documentation#6]
This page has no content: [2021-04-02.md](../blob/main/weeklynotes/2021-04-02.md)

**Comment by vedant205** [comment]
Vaishnavi said she will update this to reflect this week's notes

**Comment by agarmu** [comment]
Ok. In the future, please refrain from committing files without content, unless it is a sort of 'initial repo commit'.

**Comment by vedant205** [comment]
Okay👍
